language: node_js

node_js:
  - node

install:
  - yarn install

script:
  - yarn run build

  # prepare deployment
  - mkdir build
  - cp -rf Filters build/

notifications:
  email:
    recipients:
      - filters@adguard.com
    on_success: never
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
